### ISSUE TITLE
gulp-autoprefixer css syntax error

### ISSUE THREAD

**Issue by zoerooney** [zoerooney/Emi#35]
_From @jenniferhail on January 1, 2015 20:42_

Running gulp watch throws an unknown word error in style.css.map:3:1

I read through this thread, https://github.com/sindresorhus/gulp-autoprefixer/issues/20, but I'm not sure of the fix.

_Copied from original issue: zoerooney/yo-emi#20_

**Comment by zoerooney** [comment]
A couple things to try:
* Make sure the gulpfile is the most recent version, same with the package.json file
* Make sure Gulp is up to date (and all packages in the theme - sometimes I just delete the whole node_packages file and reinstall after updating the package.json file)
* Run `gulp styles` to see if it's the watch task or something in the styles flow (sounds like the latter)

LMK how those go and then I'll check further!

**Comment by zoerooney** [comment]
_From @jenniferhail on January 2, 2015 22:16_

I ran yo emi which should have pulled the most recent files, so I think that part is good.
Just updated Gulp globally and locally. Tried deleting the node_packages file, but I can't figure out how to reinstall it in the theme folder.
Before I deleted `node_packages` I ran gulp styles and the same error occurred.

**Comment by zoerooney** [comment]
You can reinstall the packages by running `npm install`

I'm going to move this over to the Emi issues, since it's really an Emi issue, not a generator issue.

**Comment by jenniferhail** [comment]
Running `npm install` in the theme folder after deleting the files returns `command not found`.

**Comment by zoerooney** [comment]
What do you get if you run `npm -v`, `sass -v` and `node -v`? I just ran yo emi on a new folder and everything is working as expected, so I'm thinking one of those is in need of updates.

To update Node/ NPM, you can use an installer if you've got one (like homebrew) or you can do it via the installer: http://nodejs.org/ (current version is v0.10.35)

To update Sass, you can use `sudo gem update sass` (current is 3.4.9 "Selective Steve")

To update just NPM, not Node, you can run `sudo npm update -g npm` (current is 2.1.17)

**Comment by zoerooney** [comment]
Oh wait, I ran a couple updates on mine and now I'm seeing it. I'd still check for latest versions but I'll check the Sass syntax against their updates.

**Comment by zoerooney** [comment]
It's definitely to do with gulp-ruby-sass, not Autoprefixer, from what I can tell. I'll have to look through the 1.0 docs to see how to rewrite the gulpfile for the new version - here's what I have so far but it's ignoring anything not in the main `/scss/` directory and I have to figure out how to make those work since globs/ arrays aren't supported yet:

```
var gulp = require('gulp'),
    plumber = require('gulp-plumber'),
    sass = require('gulp-ruby-sass'),
    autoprefixer = require('gulp-autoprefixer'),
    minifycss = require('gulp-minify-css'),
    newer = require('gulp-newer'),
    imagemin = require('gulp-imagemin'),
    git = require('gulp-git'),
    livereload = require('gulp-livereload'),
    lr = require('tiny-lr'),
    server = lr();

var imgSrc = 'assets/images/originals/*';
var imgDest = 'assets/images';

gulp.task('sass-main', function(){
  return sass('scss', { container: 'gulp-ruby-sass-main' }) 
      .on('error', function (err) {
          console.error('Error!', err.message);
      })
	    .pipe(gulp.dest(''))
	    .pipe(autoprefixer('last 2 version', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4'))
	    .pipe(minifycss())
	    .pipe(gulp.dest(''));
});
gulp.task('sass-pages', function(){
  return sass('scss/pages', { container: 'gulp-ruby-sass-pages' }) 
      .on('error', function (err) {
          console.error('Error!', err.message);
      })
      .pipe(gulp.dest(''))
      .pipe(autoprefixer('last 2 version', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4'))
      .pipe(minifycss())
      .pipe(gulp.dest(''));
});
gulp.task('sass-blog', function(){
  return sass('scss/blog', { container: 'gulp-ruby-sass-blog' }) 
      .on('error', function (err) {
          console.error('Error!', err.message);
      })
      .pipe(gulp.dest(''))
      .pipe(autoprefixer('last 2 version', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4'))
      .pipe(minifycss())
      .pipe(gulp.dest(''));
});
gulp.task('sass-fonts', function(){
  return sass('scss/fonts', { container: 'gulp-ruby-sass-fonts' }) 
      .on('error', function (err) {
          console.error('Error!', err.message);
      })
      .pipe(gulp.dest(''))
      .pipe(autoprefixer('last 2 version', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4'))
      .pipe(minifycss())
      .pipe(gulp.dest(''));
});

gulp.task('images', function() {
  return gulp.src(imgSrc, {base: 'assets/images/originals'})
        .pipe(newer(imgDest))
        .pipe(imagemin({ optimizationLevel: 3, progressive: true, interlaced: true }))
        .pipe(gulp.dest(imgDest));
});

gulp.task('styles', ['sass-main', 'sass-blog', 'sass-pages', 'sass-fonts']);

gulp.task('default', ['styles', 'images']);

gulp.task('watch', function() {
  // Listen on port 35729
  server.listen(35729, function (err) {
      if (err) {
        return console.log(err);
      }
  
      // Watch .scss files
      gulp.watch('scss/*.scss', ['sass-main']);
      gulp.watch('scss/pages/*.scss', ['sass-pages']);
      gulp.watch('scss/blog/*.scss', ['sass-blog']);
      gulp.watch('scss/fonts/*.scss', ['sass-fonts']);
      gulp.watch('assets/images/originals/**', ['images']);
  
    });

});
gulp.task('init', function(){
	git.init();
});
gulp.task('commit', function(){
  return gulp.src('./*')
  .pipe(git.add())
  .pipe(git.commit('initial commit'));
});
gulp.task('setup',['styles','init','commit']);
```

**Comment by jenniferhail** [comment]
I had to install Node again. Somehow it wasn't there when I ran `npm -v`, which is odd. So everything is updated now. 

Does this happen for you now? I just updated my gulpfile to match yours.

```
jhmac:BridesStyle Hail$ gulp styles
[19:47:25] Using gulpfile /Applications/AMPPS/www/bridesstyle/wp-content/themes/BridesStyle/gulpfile.js
[19:47:25] Starting 'sass-main'...
[19:47:25] Starting 'sass-blog'...
[19:47:25] Starting 'sass-pages'...
[19:47:25] Starting 'sass-fonts'...
```

**Comment by zoerooney** [comment]
Ok, found what seems to be a working solution. I just pushed an update to the gulpfile that handles this, but you also have to update the `scss/styles.scss` file so that all the imports are there (so we're not referencing an `all` file in a subfolder that has imports in it - everything gets imported in the main scss file). It seems to test correctly with the newest alpha of gulp-ruby-sass in quick tests.

**Comment by jenniferhail** [comment]
Not sure if this is still related, but now I'm having another issue.

```
[16:19:12] Starting 'watch'...
[16:19:12] Finished 'watch' after 2.7 ms
[16:19:24] Starting 'styles'...
```

Saving a .scss file starts styles but it never finishes the task.

**Comment by zoerooney** [comment]
Have you tried quitting and restarting terminal?

**Comment by elgitdemauro** [comment]
I had the same problem and solved it by a downgrade to version gulp-autoprefixer 1.0.1
